name: Backend CI

on:
    push:
        paths:
            - 'package.json'
            - 'package-lock.json'
            - '.github/workflows/backend-ci.yml'
            - 'backend/**'

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'
            - name: Show workspace files
              run: |
                  pwd
                  ls -l
            - name: Install dependencies
              run: npm ci
            - name: Install collector dependencies
              run: |
                cd backend/collector
                npm install
            - name: Install metadata-aggregator dependencies
              run: |
                cd backend/metadata-aggregator
                npm install
            - name: Debug TypeScript compilation
              run: |
                echo "Current directory:"
                pwd
                echo "Files in collector directory:"
                ls -la backend/collector/
                echo "TypeScript files in collector:"
                find backend/collector/ -name "*.ts"
                echo "TypeScript compilation output:"
                npx tsc --project backend/collector/tsconfig.json --pretty false
              continue-on-error: true
            - name: Lint & Type Check
              run: npx tsc -p backend/collector/tsconfig.json
            - name: Build packages
              run: |
                for d in backend/*; do
                  if [ -f "$d/package.json" ]; then
                    cd $d
                    npm run build
                    cd -
                  fi
                done
            - name: Build Docker images
              run: |
                  docker build -t sensorium/collector:latest backend/collector
                  docker build -t sensorium/transcoder:latest backend/transcoder
                  docker build -t sensorium/slicer:latest backend/slicer
                  docker build -t sensorium/livekit-token:latest backend/livekit-token
                  docker build -t sensorium/metadata-aggregator:latest backend/metadata-aggregator
                  docker build -t sensorium/metadata-server:latest backend/metadata-server
                  docker build -t sensorium/user-session-service:latest backend/user-session
