name: Backend CI

on:
  push:
    paths:
      - 'backend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Lint & Type Check
        run: |
          for d in backend/*; do
            if [ -f "$d/package.json" ]; then
              cd $d
              npm run build
              cd -
            fi
          done
      - name: Build Docker images
        run: |
          docker build -t sensorium/collector:latest backend/collector
          docker build -t sensorium/transcoder:latest backend/transcoder
          docker build -t sensorium/slicer:latest backend/slicer
          docker build -t sensorium/livekit-token:latest backend/livekit-token
          docker build -t sensorium/metadata-aggregator:latest backend/metadata-aggregator
          docker build -t sensorium/metadata-server:latest backend/metadata-server
          docker build -t sensorium/user-session-service:latest backend/user-session
